### PR TITLE
add ability to skip translation

### PR DESCRIPTION
**Pull request by arfelio**

### CODE REVIEW

**Comment by parndt** [comment]
Thank you, though I am not fond of the feature. @globalize/collaborators @globalize/core ?

**Comment by pranik** [comment]
What problem should solve? You can give an example of how to use it?

**Comment by arfelio** [comment]
Sorry it was a feature that can skip transaltion by giving for method
translate last parameter as false, but it was not for master version please
decline it
I am sorry

2016-07-14 13:30 GMT+03:00 Nicola Prando <notifications@github.com>:

**Comment by parndt** [comment]
No apology necessary! Thanks!

**Pull request closed without merging**
