### PR TITLE
Force version of pg gem

### PR DESCRIPTION
**Pull request by n-rodriguez**
https://github.com/rails/rails/pull/31671

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
ping!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by simi** [comment]
Thanks @n-rodriguez. pg 1.0 should be supported by latest rails, but not with currently ones supported by globalize.

**Comment by n-rodriguez** [comment]
yeah. it would have been great to use [appraisal](https://github.com/thoughtbot/appraisal).

**Pull request merged**
