### PR TITLE
Fix minor typo in arguments

### PR DESCRIPTION
**Pull request by nobuhikosawai**
## Summary
This pull requests is just to fix the typo in arguments when my last pull request (#537) is merged.
This was found by @oniram88 's [comment](https://github.com/globalize/globalize/commit/9b4199bbf5f79cac290c3164547d6d5077f8e1a8#commitcomment-18928020) and I really appreciate it.

### CODE REVIEW

**Comment by dalpo** [comment]
Thanks!

**Comment by simi** [comment]
@nobuhikosawai thanks for fix!
@dalpo what's the reason to have https://github.com/globalize/globalize/commit/a741fc448ce0469afb306d46b305e415b03c7867 on master? :(

**Comment by dalpo** [comment]
@simi Sorry I didn't notice that... :cry: 
I could rebase it. What do you think?

**Comment by simi** [comment]
Don't worry, it is actual not problem. Just a little dirty history, but it is not worth it to rewrite history because of that. :+1: on merge anyway.

**Pull request merged**
