### PR TITLE
Remove handling for locale attribute on parent model

### PR DESCRIPTION
**Pull request by tekin**
This removes some legacy code that was added to automatically keep a default translation in sync with columns on the parent table[1]. Globalize will no longer support this feature and users are expected to drop the translated columns from parent table.

[1] globalize#183

### CODE REVIEW

**Comment by parndt** [comment]
You're so cool

**Comment by tekin** [comment]
Why thank you ;)

**Comment by simi** [comment]
SICK!!!

**Comment by shioyama** [comment]
great stuff!! Much cleaner. :sparkles:

**Comment by simi** [comment]
*Just note: it will be nice to add tests to check this would not be added again by mistake.*

**Pull request merged**
