### PR TITLE
Fix for count following an order

### PR DESCRIPTION
**Pull request by basex**
PG::InvalidColumnReference was corrected in ActiveRecord https://github.com/rails/rails/issues/31783 Commit https://github.com/rails/rails/commit/6df9b69b2363734175d8869393e83e6ce8b4d7b6

Solves https://github.com/globalize/globalize/issues/608

### CODE REVIEW

**Comment by dalpo** [comment]
Great! We could finally remove that ugly workaround!

The only think I'm concerned is about the support for older rails versions  (`< 5.1.5`).
@basex Could you add a simple `::ActiveRecord::VERSION::STRING < "5.1.5"` or something like that to mantain the compatibility?

**Comment by basex** [comment]
@dalpo can you merge this PR?

**Comment by parndt** [comment]
I've restarted CI

**Comment by sergey-alekseev** [comment]
This patch actually breaks tests.

**Pull request closed without merging**
