### PR TITLE
Replace after_ callbacks with before_

### PR DESCRIPTION
**Pull request by scarfacedeb**
Beginning of discussion: https://github.com/globalize/globalize/issues/325

I replaced after_create/after_update with before_create/before_update and set autosave: true.
Now we don't need to explicitly call translations.save inside save_translations!, because autosave takes care of it for us.
Test results haven't changed (192 tests, 1 skips).

Also I added a couple of tests for the current null: false case.

I merged my current branch into the previously created before_callbacks branch and I'm not sure that it would give the best git log. Can anybody validate it for me? (I can fork globalize again and reapply all changes by hand, if it's needed)

### CODE REVIEW

**Comment by parndt** [comment]
Well I suppose this would go in version 5.1.0 instead, now.

**Comment by jonasheinrich** [comment]
Thanks for the fix and for the merge! 
@parndt Any chance this gets released soon? As far as I can see `5.0.1` doesn't include this fix. Thanks!

**Comment by parndt** [comment]
@jonasheinrich oh, that's a shame.  If this is in the master branch then I suppose it'll get released when 5.1.0 does.  I don't have any planned date for that, but as 5.0.1 is over a year old, it'd make sense!

@globalize/collaborators are we okay with releasing [this list of changes (compare view)](https://github.com/globalize/globalize/compare/v5.0.1...master) as 5.1.0?

**Comment by tomash** [comment]
Yes, it looks like a release with some deep architectural changes (callbacks!) that should be mostly compatible in terms of public api with 5.0.

**Comment by jonasheinrich** [comment]
@tomash @parndt Thanks for your replies! 
Just as a remark: The current head of the master branch somehow freezes my tests (probably some gem incompatibilities). So if you could release just that merge commit or a minimum of following commits that would be great. Thanks in advance!

**Comment by parndt** [comment]
I don't suppose there's any way we can run your tests? :)

**Comment by jonasheinrich** [comment]
Yeah, unfortunately there is no way :D. Which makes it kind of hard for you to guess the correct commit to release. So I'd say just release `40a909b14a11d677efcd2f35b0cbb6abe732cfe8`. But that is only my opinion :)

**Comment by parndt** [comment]
Could you use rebase against the globalize repository to find the commit in which they start freezing?  

You can clone globalize:

```
git clone https://github.com/globalize/globalize
``` 

Then, specify globalize as a path source:

```ruby
gem "globalize", path: "/path/to/your/local/clone"
```

Then, you can run git bisect inside the globalize directory:

```
git bisect bad master
git bisect good v5.0.1
```

And git will switch between commits, allowing you to run your test suite each time it does it and confirm whether or not it freezes.  Then you can tell bisect whether it's a "good" commit or a "bad commit".  Eventually you should track down the right commit 😄

**Comment by jonasheinrich** [comment]
@parndt Thanks for taking so much time. Yes, that's an idea I could have come up with myself. Hopefully gonna do that today.

**Comment by jonasheinrich** [comment]
@parndt Seems like the first bad commit is `c0147df067171df8865fba693fd4521219392634`. Not sure how that is possible looking at this commit. But if you could release the parent of this one (`98ab1aae7ee1af2960cb4e02a15ed80a657b79e4`, right?) it would be neat!

**Comment by parndt** [comment]
I'd rather find out why that makes your tests freeze, as it's an improvement. 
Which test freezes? 
In what way does it freeze?
Which stage of testing freezes?

**Comment by jonasheinrich** [comment]
@parndt I fixed the application (which was not the fault, not the tests). Thanks for being so persuasive :)
Just for your information: The problem was a missing `include(:translations)` such that I got an SQL error because I order by the translated name. 
So you could as well release the `HEAD` of `master`. Thanks again!

**Comment by jonasheinrich** [comment]
@parndt Any chance you can release this? Or is there anything more I can do? Thanks in advance!

**Comment by parndt** [comment]
@globalize/collaborators any objection to a release?

**Comment by simi** [comment]
I think Rails 5 is broken. I try to take a look what happened. Will be nice to release with green CI builds.

**Comment by bricesanchez** [comment]
I'm not a collaborator for globalize but rails 5 update of Refinery needs this PR merged : #505

**Comment by parndt** [comment]
That PR has a checklist which is still not showing as complete, does that sound correct to you?

**Comment by bricesanchez** [comment]
Oh i didn't see that #501 was merged, sounds correct for me.

**Pull request merged**
