### PR TITLE
Remove type check for translated fields

### PR DESCRIPTION
**Pull request by keithlayne**
#516

### CODE REVIEW

**Comment by shioyama** [comment]
@globalize/collaborators What do you think? Seems fine to me, but I don't know the background for why the restriction was put in there in the first place.

**Comment by mingsheng88** [comment]
Haven't contributed before but I believe translation should be meant for fields containing text, which was why the text is there? translation wouldn't make sense for doubles, floats, boolean etc etc. I think its just a defensive mechanism

**Comment by keithlayne** [comment]
If you switch your mindset from 'translations' to 'per-locale values' then the restriction on types makes less sense.  I could imagine use cases for lots of types if you look at it that way (including numerics and booleans).

My main argument is that globalize is a library, and therefore should provide the consumer with as much flexibility as possible.  I would like to see the type check go away completely because it doesn't make much sense to me.  On the other hand, there are lots of types that aren't included in the current type check that would make sense to translate (like JSON).  The maintenance overhead for adding types on a one-off basis would be relatively huge.  It's a slippery slope.

**Comment by parndt** [comment]
Goodbye, type check!

**Pull request merged**
