### PR TITLE
Add UUID support

### PR DESCRIPTION
**Pull request by sebastiankliem**
I've added support for using UUIDs in the translation tables when the model that should be translated uses UUIDs instead of IDs itself. Therefore I have extended create_translation_table with an option "use_uuid".

### CODE REVIEW

**Comment by parndt** [comment]
Configurable would be super nice

**Comment by sebastiankliem** [comment]
@parndt Unfortunately I do not have the time to work on this any further. I'm sorry for that.

**Comment by parndt** [comment]
@sebastiankliem that's fine, thank you so much for all of the work you have done!

**Comment by daniel-de-wit** [comment]
Just and idea, maybe we can check the delegated model for what kind of type it uses?

```
connection.create_table(translations_table_name, id: model.columns_hash[model.primary_key].type.to_sym)
```

I know this is ugly, i'm still kind of new to all this.

**Comment by gregmolnar** [comment]
I think @daniel-de-wit 's solution could be a good approach just the test suite needs to be run against postgres as well. In the meantime I think the simples solution is to alter the column in the migration:

```
Post.create_translation_table! :title => :string, :text => :text
change_column :post_translations, :post_id, :uuid
```

**Comment by abhiQmar** [comment]
This should be closed as UUID is now being supported:
[link](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/migration.rb#L73)

**Pull request closed without merging**
