### PR TITLE
Fixes for Rails 6.0 and 6.1

### PR DESCRIPTION
**Pull request by pixeltrix**
This PR makes the test suite pass locally for me using the SQLite database adapter on Rails 4.2 through to 6.1

I've tried to do the minimum possible to make it work but I have concerns about the changes for 6.0+ since Active Model has tweaked it's internals quite a bit. The Active Model API surface area is very large and I'm pretty sure I'll have missed something related to tracking changes.

### CODE REVIEW

**Comment by parndt** [comment]
@pixeltrix thanks for doing this; In parallel, because I noticed CI wasn't working properly in #769, I've fixed CI in #772 by using the Ruby organisation's setup-ruby action, but is that going to make this more difficult for you?

**Comment by pixeltrix** [comment]
@parndt it's fine, I'll just need to tweak this PR - merge #772 and I'll make the change

**Comment by parndt** [comment]
Done - thanks!

**Comment by pixeltrix** [comment]
Updated the workflow changes 👍

**Comment by parndt** [comment]
Thanks a lot @pixeltrix 🎉 

@tomash did you still want to take a look at this?

**Comment by tomash** [comment]
Great work @pixeltrix !

@parndt thanks, it's good. I thought the build errors came from extensive branching to support both pre-6 and 6-plus versions of activemodel, I was wrong. Also, long time no see! 😎

**Comment by tomash** [comment]
I think that after merging that we should update gemspec (and ensure previous versions don't allow installing with AM 6.0, maybe yank or patchlevel update?) and release a new version, @parndt

**Comment by parndt** [comment]
@tomash yep, let's release it as version 6.0.0, it looks good to me too.

Do you mean that after we release it, we should modify the master branch to target newer versions of Rails? Or do you mean that when we push this version we should restrict it to newer versions of Rails and remove the branching?

**Review by parndt — APPROVED** [review]

**Comment by parndt** [comment]
Thanks @pixeltrix, I've merged it in and I've released it as 6.0.0 🎉

**Comment by tomash** [comment]
I mean this option:

> Or do you mean that when we push this version we should restrict it to newer versions of Rails and remove the branching?

So just as you did: have Globalize versions follow more-or-less Rails version numbers (at least major number), with simple and unbranched code 😎

**Pull request merged**
