### PR TITLE
Patch query_method until Rails4

### PR DESCRIPTION
**Pull request by bricesanchez**
This PR should fix the `number?` error : https://github.com/globalize/globalize/pull/485#issuecomment-200804762

### CODE REVIEW

**Comment by bricesanchez** [comment]
Could you restart the CI build? I don't know why it fails.

**Comment by parndt** [comment]
@bricesanchez do [the failed jobs](https://travis-ci.org/globalize/globalize/jobs/124908644) pass locally?

**Comment by bricesanchez** [comment]
Locally, i've a lot of warnings but no errors : 

```ruby
Finished in 2.70639s
212 tests, 523 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by parndt** [comment]
Yeah, I see the warnings, and my tests also pass with the same Gemfile.

**Comment by pranik** [comment]
Warnings are somehow related to rake. 
If I add rake 10 to Gemfile, warnings disappears.
```ruby
gem 'rake', '10.5.0'
```

Also I noticed that if I user rake 11 I have some warnings on ` warning: loading in progress, circular require considered harmful`

**Comment by bricesanchez** [comment]
any news?

**Pull request merged**
