### PR TITLE
Support ruby 3.2 rails 7.1

### PR DESCRIPTION
**Pull request by willnet**
Add Ruby 3.2 and Rails 7.1 to CI and make it work where it didn't work

CI result is [here](https://github.com/willnet/globalize/actions/runs/6429052343).

### CODE REVIEW

**Comment by basex** [comment]
Thanks @willnet Works without problems.

@parndt can it be merged?

**Comment by parndt** [comment]
Thanks this look good but, forgive my ignorance, when did `Minitest` change and why did we have `MiniTest` 😂 ?

**Comment by willnet** [comment]
s/MiniTest/Minitest/ change seems to be done at minitest 5.0
https://github.com/minitest/minitest/commit/9a57c520ceac76abfe6105866f8548a94eb357b6

**Review by parndt — APPROVED** [review]

**Comment by parndt** [comment]
thank you 🌈

**Comment by jwoodrow** [comment]
Hi 👋  Thanks for the work on globalize, when do you think a release might happen ? The current latest gem version prevents upgrading to rails 7.1 🙏

**Comment by parndt** [comment]
https://rubygems.org/gems/globalize/versions/6.3.0 😄 enjoy

**Pull request merged**
