### PR TITLE
Update gemspec to be compatible with Rails 6.0

### PR DESCRIPTION
**Pull request by cseelus**
This PR makes Globalize compatible with Rails 6.0, see https://github.com/globalize/globalize/issues/717

### CODE REVIEW

**Comment by morgoth** [comment]
Can we have a release with this?

**Comment by sedubois** [comment]
@parndt could you cut a new release to allow using Globalize with Rails 6?

**Comment by parndt** [comment]
Just to note that version 5.3.0 has this https://rubygems.org/gems/globalize/versions/5.3.0

**Comment by stevenmichaelthomas** [comment]
@parndt @svenfuchs would it be possible to create a github release for 5.3.0?

**Comment by rpbaptist** [comment]
Maybe update the changelog as well. Don't want to be rude here, but calling this gem the "Rails I18n de-facto standard library for ActiveRecord model/data translation." I'd expect a little more.

**Comment by parndt** [comment]
@stevenmichaelthomas done - and thanks for the prompt; forgot to tag it.

**Pull request merged**
