### PR TITLE
Globalize gets a logo

### PR DESCRIPTION
**Pull request by shioyama**
globalize

I'm creating a pull request for this since there wasn't general agreement. Ref: https://twitter.com/parndt/status/391422841251315712

Here's the font: https://www.google.com/fonts/specimen/Righteous I like it, but there was some disagreement:

"awesome"
https://twitter.com/_tomash/status/391190374930079746

"not a huge fan"
https://twitter.com/svenfuchs/status/391189803485896704

I previously had another background:

globalize

From here: https://upload.wikimedia.org/wikipedia/commons/e/e4/Globe.png

but swapped it for a NASA photo.

I'm okay with anything, even scrapping this proposal entirely, or switching the background for something else. But I think we should have something. Comments/suggestions?

If anyone knows a real designer who wants to create something original for us, that would be great too (I am _not_ a designer and do not pretend to be one...)

cc @parndt @tomash @svenfuchs

### CODE REVIEW

**Comment by parndt** [comment]
I used the globe as the basis for the organisation logo too, hope @simi approves

**Comment by simi** [comment]
:trilion:
Dne 15.2.2015 23:33 "Philip Arndt" <notifications@github.com> napsal(a):

**Comment by simi** [comment]
Is there chance to get transparent background?

**Comment by parndt** [comment]
If NASA has that option, I couldn't find it

**Comment by simi** [comment]
What about http://upload.wikimedia.org/wikipedia/commons/2/22/Earth_Western_Hemisphere_transparent_background.png?

**Comment by parndt** [comment]
Ironic that it's North America, but otherwise looks good

**Comment by simi** [comment]
I don't know why, but only this part is transparent.

**Comment by parndt** [comment]
pretty normal for just North America to be the best version..

**Comment by simi** [comment]
:trollface:

**Comment by parndt** [comment]
It is set, and looks good.

**Comment by simi** [comment]
I can confirm!

**Pull request merged**
