### PR TITLE
Fix the reference translation

### PR DESCRIPTION
**Pull request by stokarenko**
It fixes [a little regression](https://github.com/globalize/globalize/pull/709/files#diff-d14f092167b54dd486cb43639c5be55de3a92bb741db0066c3415acad4429db3R242) coming in `v5.2`:

1) now we yield the translated value into the block passed to `_read_attribute`, but..
2) in terms of ActiveRecord [this block means the `missing_attribute` callback](https://github.com/rails/rails/blob/v6.0.3.4/activerecord/lib/active_record/associations/belongs_to_association.rb#L119), so it happen that..
3) `globalize` successfully translates, say, `media_id` to `5` and yields the value into `missing_attribute` callback, effectively..
4) raising pretty weird `ActiveModel::MissingAttributeError: missing attribute: 5` exception.

This only happen when we define the foreign reference as translated attribute (don't ask me why.. ;) )

### CODE REVIEW

**Comment by stokarenko** [comment]
Hey all! )

In case if the change is good enough - is there a chance to release the same against `v5` as well? )

BTW, Seems that CI configuration is broken (

**Comment by parndt** [comment]
@stokarenko thanks for letting us know, I've fixed CI - can you merge master into this branch please? I can't edit the PR.

**Comment by stokarenko** [comment]
@parndt merged the master, seems like Rails 4.2 is broken though..

will take a look asap )

**Comment by stokarenko** [comment]
@parndt fixed the specs )

**Review by parndt — APPROVED** [review]

**Comment by parndt** [comment]
Thank you @stokarenko - could you please add this to the CHANGELOG.md file?

**Review by parndt — APPROVED** [review]

**Comment by stokarenko** [comment]
@parndt sure thing, done )

Is it possible to release the same against `v5`? I'm ready to prepare the corresponding PR )

**Comment by parndt** [comment]
Sure if you're happy to do all the work @stokarenko and tell me which version it's patching 👍

**Comment by stokarenko** [comment]
@parndt roger that, on my way! )

I need just a `5-3-stable` upstream branch to begin with and use it as a target for PR )
Could you checkout `v5.3.0` and push it as `5-3-stable` branch please? )

**Comment by parndt** [comment]
@stokarenko done 😄

**Pull request merged**
