### PR TITLE
Provide Rails 8.x compatibility

### PR DESCRIPTION
**Pull request by jules-w2**
The `serialize` method now no longer accepts the second argument
`class_name_or_coder`. We are still using this, so we're going to keep
using it to provide backward compatibility, but when we call `super` we
will discard this argument.

### CODE REVIEW

**Comment by matgaw** [comment]
This needs to be merged ASAP and released. No way of using globalize with rails 7.2 at the moment, and with 7.1 issues a ton of deprecation warning due to serialize issue....

**Comment by basex** [comment]
@parndt can this be merged? We are using these changes in production without issues.

**Comment by parndt** [comment]
@basex @jules-w2 thanks for the work! Once CI passes this should be OK 😄

**Comment by imamdg** [comment]
Hi, any update on this MR? We are looking to upgrade rails to 7.2, waiting for globalize compatibility/

**Comment by marshluca** [comment]
This PR works good for our project, hope it can be merged and released.

**Comment by 2called-chaos** [comment]
> @basex @jules-w2 thanks for the work! Once CI passes this should be OK 😄

It's going to be tricky/dirty to fix these two tests. The question is if we just want to create a version which drops older Rails support? Then we just need to change the usage of `serialize` within this project (easy) and we could maybe drop this patching (and relying on mimicing rails logic) completely by fiddling with the internals differently :D

Instead of this manual tracking there we could access/use this in the enable_serializable_attribute thing where all this stems from?

    record.class.attribute_types["translated_attribute_name"].is_a?(ActiveRecord::Type::Serialized)
    # => true

    record.class.attribute_types["translated_attribute_name"].coder
    # => #<ActiveRecord::Coders::YAMLColumn:......>

I could do a PR if we want to do that

**Comment by parndt** [comment]
It's entirely reasonable at this point to drop unsupported Rails versions if it's hard to maintain them. We would need a major version release to do so, which is OK.

**Comment by lukaselmer** [comment]
We want to upgrade to Rails 7.2 too, and this is the only blocking issue for us. Would be great if this gets merged asap.

I also think that people stuck with `'activerecord', '= 4.2'` or `rails < 7` don't update/upgrade `globalize` 🤔

**Comment by parndt** [comment]
> We want to upgrade to Rails 7.2 too, and this is the only blocking issue for us. Would be great if this gets merged asap.

@lukaselmer happy to merge this when CI passes, is that something you're able to help with?

**Comment by zopelee** [comment]
@lukaselmer, a temporary solution for us:

put this in Gemfile:

`gem 'globalize', github: 'globalize/globalize', ref: 'refs/pull/820/head'`

**Comment by jules-w2** [comment]
Hello all,

I just made a new commit to make it compatible with rails 8.

**Comment by parndt** [comment]
@jules-w2 thanks - I've approved CI (for some reason I have to do this every time) and it's not passing unfortunately

**Comment by wt-l00** [comment]
Thanks for this pull request.

I think the reason CI is failing is related to this PR: [Allow to define the default column serializer by casperisfine · Pull Request #47463 · rails/rails](https://github.com/rails/rails/pull/47463) .  In this PR, the coder specification has been changed to a keyword argument. Also, `default_column_serializer` is defined as Coders::YAMLColumn and the coder specification is not working well in the failing test case. ref: https://github.com/rails/rails/pull/47463/files#diff-308fa065a337d20ad65f191f01ce9ab7ac947209763fd3ba9dc7d64a3f39d7f4

I think this patch will pass the test, but I think it would be better to add a proper test case... . Another issue is how to specify the type keyword for the serialize method. I can't seem to come up with any good ideas, so if you have any suggestions, please let me know.

```diff
diff --git a/lib/patches/active_record/rails7_1/serialization.rb b/lib/patches/active_record/rails7_1/serialization.rb
index 6288104..fead23b 100644
--- a/lib/patches/active_record/rails7_1/serialization.rb
+++ b/lib/patches/active_record/rails7_1/serialization.rb
@@ -2,8 +2,6 @@ module Globalize
   module AttributeMethods
     module Serialization
       def serialize(attr_name, class_name_or_coder = Object, **options)
-        super(attr_name, **options)
-
         coder = if class_name_or_coder == ::JSON
                   ::ActiveRecord::Coders::JSON
                 elsif [:load, :dump].all? { |x| class_name_or_coder.respond_to?(x) }
@@ -12,6 +10,7 @@ module Globalize
                   ::ActiveRecord::Coders::YAMLColumn.new(attr_name, class_name_or_coder)
                 end
 
+        super(attr_name, coder:, **options)
         self.globalize_serialized_attributes = globalize_serialized_attributes.dup
         self.globalize_serialized_attributes[attr_name] = coder
       end
```

**Comment by 2called-chaos** [comment]
> I think the reason CI is failing is related to this PR: [Allow to define the default column serializer by casperisfine · Pull Request #47463 · rails/rails](https://github.com/rails/rails/pull/47463) .

Yes but the problem is not really that. The test is failing because to get the same behaviour as before you also need to give it a type or the attribute will default to nil instead of type.new but type is not supported in older versions. Hence we kinda need a version aware test but we also still can get rid of this coder tracking (I'm just not sure how far back this is exposed by AR)

**Comment by parndt** [comment]
Please see also #825

**Comment by rocket-turtle** [comment]
@jules-w2 maybe you can have a look at https://github.com/globalize/globalize/pull/825

@zopelee could you please check my other branch if it is working for you too.

**Comment by parndt** [comment]
I've merged #824 and #825 which should help a lot with this - can you please check @jules-w2 ?

**Comment by jules-w2** [comment]
hey @parndt,

this pull requests #824  and #825 are for rails 7.2.. All my apps are in rails 8.0.
I can't test this PR.

the only thing i can confirm is that my pull-request (#820) works fine on rails 7.2 and rails8. i've been using it in production on all my apps for over a year.

**Comment by parndt** [comment]
Awesome that's good info anyway thanks @jules-w2

**Comment by rocket-turtle** [comment]
Added Rails 8.0 and Ruby 3.3 to the test matrix https://github.com/globalize/globalize/pull/826/files

**Comment by parndt** [comment]
> Added Rails 8.0 and Ruby 3.3 to the test matrix https://github.com/globalize/globalize/pull/826/files

Merged!

**Comment by parndt** [comment]
I tried to resolve PR conflicts, but @jules-w2 can you please check (if you have time) if the patch works for you still? Or if we can use this serializer for Rails 8? https://github.com/globalize/globalize/blob/2205b1eadeaec69d0b7ae0a4ab7fdb5b1ebcded1/lib/patches/active_record/rails7_2/serialization.rb

**Comment by jules-w2** [comment]
hey @parndt 

I just tested the 2 main branches on my rails 8 apps. Both of them works fine 🚀

- https://github.com/globalize/globalize/commit/2205b1eadeaec69d0b7ae0a4ab7fdb5b1ebcded
- https://github.com/jules-w2/globalize/commit/b99716b000889c753ef7150c4cc9cafb7f4364cd

Personally I think your main branch is ready to be released  for a production (on v7.0.0)

Bests

**Comment by parndt** [comment]
Awesome, thanks so much @jules-w2 🎉 really appreciated

**Comment by jules-w2** [comment]
hey @parndt

Do you have an expected release date for the new version?

Bests

**Pull request closed without merging**
