### PR TITLE
Add issue template.

### PR DESCRIPTION
**Pull request by simi**
It will be nice to point to this template in [CONTRIBUTING.md](https://github.com/globalize/globalize/blob/master/CONTRIBUTING.md). Can anyone provide some good copy for that?

### CODE REVIEW

**Comment by parndt** [comment]
What's this do?

**Comment by simi** [comment]
Basic template how to reproduce an issue. It will be nice to have script to reproduce issue and this can make it easier to create one IMHO (actually it is stolen from rails and modified).

**Comment by simi** [comment]
@shioyama @scarfacedeb any ideas? Do you think this is useful at all?

**Comment by scarfacedeb** [comment]
I like the idea.

But it's often the particular configuration of someone's app and models, or an interaction of globalize and other gems that results in an issue.
And this kind of issues would probably disappear when you try to reproduce them using your template.

With that in mind, I think it's worth mentioning in the CONTRIBUTING.md or in a wiki the basic steps that could help to pinpoint a source of some issues.

For example, for the issues with other gems we can advise to remove any other macros from the model one by one. (e.g. https://github.com/globalize/globalize/issues/391)

Also, we could mention that it's better to show the model and schema.rb files in the issue right away.
It would allow to skip the first question that often asks to show those files.

**Comment by simi** [comment]
That's the spirit. This is minimal template. You should copy your behavior to this template piece by piece to get your test case failing. You'll get schema and model also.

According to #391 the process will be similar, but just reversed. You'll be copying behavior one by one to our template. Once you'll have a minimal script to reproduce, you can rethink if that's really a globalize issue.

This idea is stolen from Rails where this works very well.

**Comment by scarfacedeb** [comment]
Cool! I didn't know that Rails is also using it.

I suppose this minimal template isn't the final result, because it won't run as is.
How do you plan to make it run out of the box - a little rails app or more stripped down version with a couple of files (e.g. Gemfile, reproduce.rb, models.rb, etc)?

**Comment by simi** [comment]
Actually it runs out of the box here. What problems do you have?

**Comment by scarfacedeb** [comment]
It was only my own stupidity :)
It runs out of the box now.

I think this minimal template is enough to give people an idea about what goes where.
The only thing missing is some instruction on how to use it in README.

**Comment by simi** [comment]
Yes, in README and CONTRIBUTING. Do you have any idea for copy for that?

**Comment by scarfacedeb** [comment]
I think it should be something related to reduced test case.

> Isolate the demonstrable problem — Try to reproduce the problem with the Demo or with a reduced test case that includes the least amount of code necessary to reproduce the problem.


As an example: https://github.com/davatron5000/FitVids.js/blob/055bbd5a212e587ffba1604f08f75f572c3068b0/CONTRIBUTING.md

More general post about it: http://css-tricks.com/reduced-test-cases/

**Comment by simi** [comment]
Rails text: http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-a-self-contained-gist-for-active-record-and-action-controller-issues

**Comment by shioyama** [comment]
Hey sorry late to this, I'd be happy for any improvement to [CONTRIBUTING](https://github.com/globalize/globalize/blob/f1d7b06d53a5820a9e6421ae6f4357906d98292b/CONTRIBUTING.md), I just put it there a while back because we had no instructions at all at the time. The script seems like a reasonable place to start.

How about: "If you are filing a bug report, please consider adapting the provided template to reproduce the problem with minimal dependencies."

I like @scarfacedeb's text as well.

**Comment by shioyama** [comment]
We should also update the existing contributing text to reflect changes to globalize versions and branches.

**Comment by simi** [comment]
ping @shioyama

**Pull request merged**
