### PR TITLE
Add Rails > 6.0 compatibility

### PR DESCRIPTION
**Pull request by sedubois**
Ref: https://github.com/globalize/globalize/issues/753#issuecomment-615241727

To test I've just upgraded my Gemfile with `gem 'rails', github: 'rails/rails'` and `gem 'globalize', github: 'sedubois/globalize', branch: 'rails-6-1'`, ran bundler, started the app and checked that some globalized models loaded successfully.

### CODE REVIEW

**Comment by sedubois** [comment]
The mysql tests fail just like on master so should be unrelated to this change (`mysql: [Warning] Using a password on the command line interface can be insecure.`).

**Comment by parndt** [comment]
Perhaps we need something like this to fix MySQL :

https://github.com/norman/friendly_id/pull/940

**Comment by sedubois** [comment]
@parndt fixed here: https://github.com/globalize/globalize/pull/756

I can rebase this branch when it's merged.

**Comment by simi** [comment]
@sedubois merged

**Comment by sedubois** [comment]
Thanks @simi, now the tests are green.

**Comment by parndt** [comment]
Thanks @sedubois and @simi  😄

**Comment by sedubois** [comment]
Thanks @parndt, would it be possible to get a release with this? 

and Globalize-versioning needs a similar update too: https://github.com/globalize/globalize-versioning/pull/23

**Comment by parndt** [comment]
I've released [an alpha gem](https://rubygems.org/gems/globalize/versions/6.0.0.alpha.1)

Once Rails 6.1 is out and it works we can revisit the gem release. 😄

**Pull request merged**
