### PR TITLE
Bug fix for saving changes in same translation

### PR DESCRIPTION
**Pull request by ASnow**
see test

### CODE REVIEW

**Comment by parndt** [comment]
Hi @ASnow quite a bit has changed on this repository lately, are you happy to look into this again based on the more recent code please?

**Comment by ASnow** [comment]
Hi @parndt I merged updates. It looks working

**Comment by parndt** [comment]
@globalize/collaborators please review if you can as this is a fairly big change :smile:

**Comment by ASnow** [comment]
bug is still working, it's realy make me creazy)

**Comment by ASnow** [comment]
up

**Comment by ASnow** [comment]
up

**Comment by ASnow** [comment]
up

**Comment by parndt** [comment]
Thanks! Sorry that it took so long to get back to this.

**Comment by krisdigital** [comment]
@ASnow I am getting a `cannot load such file -- pry` error after the commit, using with Rails 4.2.5..

**Comment by ASnow** [comment]
https://github.com/globalize/globalize/pull/495

**Pull request merged**
