### PR TITLE
ordering by translated attributes

### PR DESCRIPTION
**Pull request by thomasmaas**
Join the translations table for translated attributes

### CODE REVIEW

**Comment by thomasmaas** [comment]
@parndt anything i can do to speed up the process of merging this pr? Thanks.

**Comment by parndt** [comment]
@thomasmaas looks good, but can you please add a changelog entry?

**Comment by thomasmaas** [comment]
Sure, there you go.

**Comment by parndt** [comment]
Thanks! It just helps to track this down for anyone who later has an issue. (though hopefully not)
:+1:

**Comment by ppostma** [comment]
We just updated to the latest master of globalize which includes this change and noticed duplicate results for some of our queries.

Before this change:
```
ProjectNews.order(created_at: :desc)
=> SELECT "project_news".* FROM "project_news"  ORDER BY "project_news"."created_at" DESC

ProjectNews.order(created_at: :desc).count
=> 151
```

After:

```
ProjectNews.order(created_at: :desc)
=> SELECT "project_news".* FROM "project_news" INNER JOIN "project_news_translations" ON "project_news_translations"."project_news_id" = "project_news"."id" WHERE "project_news_translations"."locale" IN ('nl', 'en')  ORDER BY "project_news"."created_at" DESC

ProjectNews.order(created_at: :desc).count
=> 254
```

Changing the query to `ProjectNews.order("#{ProjectNews.table_name}.created_at DESC")` makes it restore to the old behavior. But just wondering, was a behavior change like this intended?

**Pull request merged**
